/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Factory__factory } from "./Factory__factory";
export { FactoryByClone__factory } from "./FactoryByClone__factory";
