/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface FactoryInterface extends utils.Interface {
  functions: {
    "baseClonableContract()": FunctionFragment;
    "cloneContract()": FunctionFragment;
    "createNewInstance()": FunctionFragment;
    "method1()": FunctionFragment;
    "method2()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "baseClonableContract"
      | "cloneContract"
      | "createNewInstance"
      | "method1"
      | "method2"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "baseClonableContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cloneContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createNewInstance",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "method1", values?: undefined): string;
  encodeFunctionData(functionFragment: "method2", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "baseClonableContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cloneContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createNewInstance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "method1", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "method2", data: BytesLike): Result;

  events: {};
}

export interface Factory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: FactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    baseClonableContract(overrides?: CallOverrides): Promise<[string]>;

    cloneContract(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createNewInstance(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    method1(overrides?: CallOverrides): Promise<[string]>;

    method2(overrides?: CallOverrides): Promise<[string]>;
  };

  baseClonableContract(overrides?: CallOverrides): Promise<string>;

  cloneContract(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createNewInstance(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  method1(overrides?: CallOverrides): Promise<string>;

  method2(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    baseClonableContract(overrides?: CallOverrides): Promise<string>;

    cloneContract(overrides?: CallOverrides): Promise<void>;

    createNewInstance(overrides?: CallOverrides): Promise<void>;

    method1(overrides?: CallOverrides): Promise<string>;

    method2(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    baseClonableContract(overrides?: CallOverrides): Promise<BigNumber>;

    cloneContract(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createNewInstance(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    method1(overrides?: CallOverrides): Promise<BigNumber>;

    method2(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    baseClonableContract(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    cloneContract(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createNewInstance(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    method1(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    method2(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
